apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comments-system.fullname" . }}-frontend
  labels:
    app: comments
    component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend | default 1 }}
  selector:
    matchLabels:
      app: comments
      component: frontend
  template:
    metadata:
      labels:
        app: comments
        component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.service.frontend.port | default 8080 }}
          env:
            - name: BACKEND_API_URL
              value: {{ printf "http://%s-backend-api:%d" (include "comments-system.fullname" .) (int .Values.service.backendApi.port) | quote }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources: {}
          {{- end }}