apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comments-system.fullname" . }}-backend-data
  labels:
    app: comments
    component: backend-data
spec:
  replicas: {{ .Values.replicaCount.backendData }}
  selector:
    matchLabels:
      app: comments
      component: backend-data
  template:
    metadata:
      labels:
        app: comments
        component: backend-data
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend-data
          image: "{{ .Values.images.backendData.repository }}:{{ .Values.images.backendData.tag }}"
          ports:
            - containerPort: {{ .Values.service.backendData.port }}
          env:
            - name: MONGO_URL
              value: "mongodb://{{ .Values.mongodb.user }}:{{ .Values.mongodb.password }}@{{ include "comments-system.fullname" . }}-mongo:27017/{{ .Values.mongodb.database | default "commentsdb" }}"
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources: {}
          {{- end }}