apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comments-system.fullname" . }}-backend-api
  labels:
    app: comments
    component: backend-api
spec:
  replicas: {{ .Values.replicaCount.backendApi | default 1 }}
  selector:
    matchLabels:
      app: comments
      component: backend-api
  template:
    metadata:
      labels:
        app: comments
        component: backend-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend-api
          image: "{{ .Values.images.backendApi.repository }}:{{ .Values.images.backendApi.tag }}"
          ports:
            - containerPort: {{ .Values.service.backendApi.port | default 5000 }}
          env:
            - name: BACKEND_DATA_URL
              value: {{ printf "http://%s-backend-data:%d" (include "comments-system.fullname" .) (int .Values.service.backendData.port) | quote }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          {{- else }}
          resources: {}
          {{- end }}